version: '3'

services:
  redis:
    image: redis
  rp:
    build: .
    container_name: rp
    command: rp
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
      - "6379:6379"
    depends_on:
      - redis
